name: kernel-bazel

on:
  push:
    branches:
      - KSU
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show repo tree
        run: |
          pwd
          ls -la
          find . -maxdepth 4 -type f | sort | sed -n '1,250p'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            bash \
            bc \
            bison \
            build-essential \
            ccache \
            curl \
            flex \
            git \
            libelf-dev \
            libssl-dev \
            lld \
            llvm \
            ninja-build \
            openjdk-17-jdk \
            python3 \
            python3-pip \